---
deployment:
  tasks:
    # Set deployment path - SESUAIKAN dengan username cPanel Anda
    - export DEPLOYPATH=/home/username/api-payment.regalpaw.id/

    # Copy all files to deployment directory
    - /bin/cp -R * $DEPLOYPATH

    # Navigate to deployment directory
    - cd $DEPLOYPATH

    # Install production dependencies only
    - npm ci --production

    # Build TypeScript to JavaScript
    - npm run build

    # Create restart file to reload Passenger
    - mkdir -p $DEPLOYPATH/tmp
    - touch $DEPLOYPATH/tmp/restart.txt

    # Set proper permissions
    - chmod -R 755 $DEPLOYPATH

    # Create logs directory if not exists
    - mkdir -p /home/username/logs
