// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Prefer build-time env vars so production keys are injected at build/deploy time.
// Ensure these are set on Vercel (or your hosting) and NOT committed to source.
// Do NOT include secret keys in source. We intentionally do not provide a
// secret fallback here to avoid leaking credentials.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) ?? '';
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/* eslint-disable @typescript-eslint/no-explicit-any */
// Use a noop storage to avoid persisting sessions in client-side localStorage.
const noopStorage: any = {
  getItem: (_: string) => null,
  setItem: (_: string, __: string) => undefined,
  removeItem: (_: string) => undefined,
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Do NOT persist sessions client-side for cookie-based auth flow. Using
    // a noop storage prevents supabase-js from writing to localStorage.
    storage: noopStorage as any,
    // Do not persist session across reloads/tabs — server will manage session
    // via HttpOnly cookies (refresh flow implemented server-side).
    persistSession: false,
    // Disable automatic refresh token behavior in the client. The server
    // handles refresh using the HttpOnly cookie.
    autoRefreshToken: false,
    // Keep URL session detection for OAuth redirects if necessary.
    detectSessionInUrl: true,
  }
});

// Warn in development if env vars are missing so developers notice and set them
// locally (but do not commit secrets to the repository).
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY.\n' +
    'Set these in your .env.local or hosting provider environment variables.\n' +
    'Do NOT commit real keys to source control.');
}