// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Prefer build-time env vars so production keys are injected at build/deploy time.
// Ensure these are set on Vercel (or your hosting) and NOT committed to source.
// Do NOT include secret keys in source. We intentionally do not provide a
// secret fallback here to avoid leaking credentials.
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) ?? '';
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) ?? '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use localStorage to persist the session in the browser. This stores the
    // access token + refresh token (encrypted by Supabase) so the user stays
    // signed-in across reloads.
    storage: localStorage,
    // Persist session across tabs / reloads
    persistSession: true,
    // Automatically refresh the access token using the refresh token when it
    // expires. This keeps the user authenticated without prompting for login.
    autoRefreshToken: true,
    // Detect and parse the auth session in URL fragments after OAuth redirects.
    // This is useful if you use `supabase.auth.signInWithOAuth` which returns
    // the session in the URL on redirect.
    detectSessionInUrl: true,
  }
});

// Warn in development if env vars are missing so developers notice and set them
// locally (but do not commit secrets to the repository).
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY.\n' +
    'Set these in your .env.local or hosting provider environment variables.\n' +
    'Do NOT commit real keys to source control.');
}